name: Check Markdown Links

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Links 🔍
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          args: --verbose --no-progress './*.md'
          fail: true
          format: markdown
          output: ./lychee/out.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report 🔗
          content-filepath: ./lychee/out.md
          labels: report, automated issue
          body: |
            A link checker scan has found broken links in the repository's markdown files.
            
            ### Files Scanned
            - All markdown (*.md) files in the root directory
            
            ### Results
            See below for the detailed report of broken links: